### ISSUE TITLE
hexo g 不报错 js css不加载

### ISSUE THREAD

**Issue by lionker** [Mrminfive/hexo-theme-skapp#101]
hexo clean 已做
hexo g 不报错
hexo s    本地预览 css js都不加载
![本地预览图片](https://raw.githubusercontent.com/lionker/web-notes/master/QQ%E6%88%AA%E5%9B%BE20190318145003.png)

**Comment by lionker** [comment]
已解决  没有配置hexo-renderer-scss

**Comment by gaohanas** [comment]
我的问题和你的一样，到底哪里配置啊
