### ISSUE TITLE
disqus integration

### ISSUE THREAD

**Issue by roccomuso** [Mrminfive/hexo-theme-skapp#12]
Does it support disqus as comment system?

**Comment by Mrminfive** [comment]
Using [gitalk](https://github.com/gitalk/gitalk)

**Comment by roccomuso** [comment]
@Mrminfive so that's a no? any plan to support disqus in the near future?

**Comment by BruceYuj** [comment]
@roccomuso  Mrminfive has added disqus in the theme.
