### ISSUE TITLE
你上次说可以直接merge，是邀请我为合作者了吗？

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#19]

**Comment by BruceYuj** [comment]
@Mrminfive

**Comment by Mrminfive** [comment]
是啊

发自我的 iPhone

在 2017年10月22日，09:48，JunYu <notifications@github.com<mailto:notifications@github.com>> 写道：


@Mrminfive<https://github.com/mrminfive>

**Comment by BruceYuj** [comment]
我 git clone下你的库，修改后提交，发现没有权限。
![hexo-theme-skapp1](https://user-images.githubusercontent.com/19621739/31857438-35753d8e-b711-11e7-93ae-d05f48fcb2b2.PNG)

**Comment by BruceYuj** [comment]
@Mrminfive

**Comment by Mrminfive** [comment]
呃，我去看看，不怎么熟github上的操作

发自我的 iPhone

在 2017年10月22日，10:10，JunYu <notifications@github.com<mailto:notifications@github.com>> 写道：


@Mrminfive<https://github.com/mrminfive>

**Comment by Mrminfive** [comment]
![31857519-3da4516e-b713-11e7-9bdd-92c81713357d](https://user-images.githubusercontent.com/24197735/31857527-66e31a24-b713-11e7-8c66-9f237a6a7e5d.png)

它是这么描述的啊

**Comment by BruceYuj** [comment]
ok，你邀请后，我应该收到一个通知(但是我没有收到通知)

**Comment by BruceYuj** [comment]
Settings =>Collaborators

**Comment by Mrminfive** [comment]
你现在已经是了

**Comment by Mrminfive** [comment]
https://github.com/Mrminfive/hexo-theme-skapp/invitations

**Comment by BruceYuj** [comment]
现在ok了，之前没有通知，现在直接用邀请链接可以了。

**Comment by Mrminfive** [comment]
那就行，今天我会把之前issues提的问题修改上去，记得pull仓库

**Comment by BruceYuj** [comment]
我今天把之前roccomuso 提的en的语法错误给修复了。push之前记得pull下。
