### ISSUE TITLE
文档更新

### ISSUE THREAD

**Issue by Mrminfive** [Mrminfive/hexo-theme-skapp#20]
我添加了google统计和disqus，更新了下中文文档，能麻烦你更新下英文文档吗？另外，你现在的gitalk还能评论吗？我怎么感觉github把这种使用issue的方式给封了

**Comment by Mrminfive** [comment]
@BruceYuj

**Comment by BruceYuj** [comment]
@Mrminfive  我今天晚上更新一下

**Comment by BruceYuj** [comment]
@Mrminfive  gitalk还是可以评论的。之前我也遇到过issue里面有记录，但是具体页面仍然叫我初始化issue的问题。

**Comment by Mrminfive** [comment]
可能是我的网络有问题，现在又不会了
