### ISSUE TITLE
nodejieba分词库安装问题

### ISSUE THREAD

**Issue by hackenhu** [Mrminfive/hexo-theme-skapp#23]
根据安装步骤，我是windows 环境，先执行了
`npm install -g windows-build-tools`
`npm install -g node-gyp`

再执行安装node依赖
`npm install --save hexo-autoprefixer hexo-filter-cleanup hexo-generator-feed hexo-generator-sitemap hexo-renderer-sass hexo-renderer-swig mamboer/lunr.js moment node-sass object-assign`

最后nodejieba报错，请问这怎么解决，试了把目录删掉，重新生成一个新的，再重复步骤，依然是报这个错。
![image](https://user-images.githubusercontent.com/2282554/33473938-747ce1fa-d6b3-11e7-9a35-faebf8a13239.png)

**Comment by BruceYuj** [comment]
node-gyp的rebuild问题，你的window具体的版本是什么？
你单独运行 node-gyp rebuild命令看看是否能够成功用node-gyp

**Comment by hackenhu** [comment]
系统是windows 10
单独运行node-gyp rebuild还是报错了
`gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\hacken\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hacken\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\develop\hexo\skapp
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
`

**Comment by hackenhu** [comment]
系统是windows 10
单独运行node-gyp rebuild还是报错了

gyp: binding.gyp not found (cwd: D:\develop\hexo\skapp) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\hacken\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hacken\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\develop\hexo\skapp
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

**Comment by BruceYuj** [comment]
@hackenhu  不好意思，这两天出去浪了，回复晚了。
建议先看一下，node-gyp的官方说明以及对应的安装方法： [node-gyp](https://www.npmjs.com/package/node-gyp)

**Comment by hackenhu** [comment]
@Mrminfive python 环境变量配置了，这个可以确定，主要还是 node-gyp 安装的问题，晚上我再试试

**Comment by BruceYuj** [comment]
@hackenhu  我之前用过一台win10安装过，没有碰到这类问题。

**Comment by hackenhu** [comment]
@BruceYuj 我是不是得把相关的nodejs，python 环境这些卸载重新安装？然后再来试会不会好一点，还有nodejs，python有版本要求吗

**Comment by BruceYuj** [comment]
windows-build-tools 里面有python2.7, 应该跟nodejs没什么关系

**Comment by BruceYuj** [comment]
@hackenhu  我星期天研究一下这个问题，你可以先卸载下安装的windows-build-tools和node-gyp，重新安装配置。

**Comment by hackenhu** [comment]
@BruceYuj  你好，应该是我环境不干净，刚刚已安装好了，能访问主页，但是点文章和其他栏目，页面出不来，所需的JS 全部404找不到路径，请问这是什么情况？

**Comment by hackenhu** [comment]
@BruceYuj 路径生成的不对，http://localhost:4000/2017/12/09/hello-world/js/common/utils.js
这个目录下没有js这些，只有一个html
还有 #7  楼说的_config.yml 这个文件，是编辑博客根目录的，还是hexo-theme-skapp目录下的

**Comment by BruceYuj** [comment]
@hackenhu 是根目录下的 _config.yml

**Comment by BruceYuj** [comment]
skapp中使用了hexo-filter-cleanup这个插件(可以用来合并压缩js文件)，你报的错是因为js文件没有合并。

**Comment by hackenhu** [comment]
@BruceYuj @Mrminfive  解决了，多生成了几次，不知道什么原因，感谢

**Comment by BruceYuj** [comment]
@hackenhu  应该的

**Comment by Mrminfive** [comment]
@BruceYuj 点个👍

**Comment by williamHappy** [comment]
![image](https://user-images.githubusercontent.com/19304825/35029553-6c869bf0-fb96-11e7-8747-4064007bbe1e.png)
同样的出现问题，首页可以访问，其他页面找不到相应的js

**Comment by BruceYuj** [comment]
@williamHappy 这是很可能是由于之前你的node依赖库安装失败，导致`hexo-filter-cleanup`没有安装成功，建议你删掉node_modules文件夹，清理环境，然后重新`npm install`

**Comment by williamHappy** [comment]
@BruceYuj 删除node_modules,重新npm install,你说清理环境，是怎么清理？没做这步操作

**Comment by BruceYuj** [comment]
@williamHappy 按照你的错误，清理环境就只需要输出node_modules，重新安装即可。

**Comment by williamHappy** [comment]
@BruceYuj 没有错误  就删除了node_nodules,然后重新npm install安装了，结果还是一样的

**Comment by williamHappy** [comment]
@BruceYuj 可以加下你的qq吗，请教一下你

**Comment by BruceYuj** [comment]
加我微信好了，你去我blog下面扫我二维码www. bruceyj. com

**Comment by williamHappy** [comment]
@BruceYuj 多谢多谢
