### ISSUE TITLE
在 /source/_data 目录下创建 contact.yml 文件将在页面底部生成相应的标签链接

### ISSUE THREAD

**Issue by feelscoder** [Mrminfive/hexo-theme-skapp#26]
找不到_data目录，自己创建目录后配置contact.yml还是不行

**Comment by BruceYuj** [comment]
@feelscoder  _data目录是自己创建的。不行是指报错了还是本地服务器起了后没有对应的显示，如果是后者，你可以去浏览器dev tools看看是否有报错。如果有，贴出具体的报错。

**Comment by BruceYuj** [comment]
@feelscoder  该问题是否已解决，如果已解决，可以close

**Comment by feelscoder** [comment]
已解决，感谢耐心解答
