### ISSUE TITLE
请问首页的文章的简介是如何设置的

### ISSUE THREAD

**Issue by myloft** [Mrminfive/hexo-theme-skapp#27]
配置完成后没有显示文章简介，只有空白

**Comment by BruceYuj** [comment]
![description](https://user-images.githubusercontent.com/19621739/34335798-9bdb0984-e98c-11e7-9322-90fdf91135dc.PNG)
@myloft  如果你说的是这里的话，应该在根_config.yml中设置`description: something you want`,这个在readme.md应该是有介绍的

**Comment by myloft** [comment]
是文章的简介，改如何设置呢
<img width="167" alt="post" src="https://user-images.githubusercontent.com/25258169/34336328-2915ab5c-e991-11e7-928b-919cb1810a90.png">

**Comment by BruceYuj** [comment]
@myloft  我已经更新了README,设置方法在  *文章基本配置* 一节，配置`subtitle: your subtitle`
