### ISSUE TITLE
如何修改所有的字体样式

### ISSUE THREAD

**Issue by feelscoder** [Mrminfive/hexo-theme-skapp#29]
比如想把字体改为汉仪旗黑或者平方。

**Comment by BruceYuj** [comment]
@feelscoder  README中的*personalized configuration*

**Comment by feelscoder** [comment]
@BruceYuj 是在这里面修改的font-family，但是修改后没有效果

**Comment by BruceYuj** [comment]
@feelscoder  我测试了下，是可以的。你可以修改后，dev tool下看下为什么失败，应该是浏览器字体渲染选择的问题。

**Comment by feelscoder** [comment]
能贴一下你修改那个地方的代码吗？我这边改了不行

**Comment by BruceYuj** [comment]
`themes->hexo-theme-skapp->source->scss->_theme.scss`

**Comment by BruceYuj** [comment]
@feelscoder  修改成功了吗？
