### ISSUE TITLE
卡片布局问题

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#3]
看你的DEMO，卡片高度不一致时，会出现大片留白(但看你的截图是等高等宽的).
是否是瀑布式布局出现问题。

**Comment by Mrminfive** [comment]
能有详细的效果截图么？

**Comment by BruceYuj** [comment]
![skapp](https://user-images.githubusercontent.com/19621739/31239117-a67b50d0-aa2e-11e7-9ddc-1d7c781bfd3e.PNG)

**Comment by Mrminfive** [comment]
应该是因为多行省略不兼容的问题，能问下你用的浏览器及版本吗，后面会对这个兼容问题做修复

**Comment by BruceYuj** [comment]
firefox 56.0(32位)下会出现该问题；chrome没问题

**Comment by BruceYuj** [comment]
edge同样也会出现该问题

**Comment by Mrminfive** [comment]
兼容bug已修复
