### ISSUE TITLE
archives页面没有加分页逻辑

### ISSUE THREAD

**Issue by mrdear** [Mrminfive/hexo-theme-skapp#30]
主题很赞,正在切换中发现一个小问题, archives没有分页,对于一年的文章还是挺多的,但是该页面没有做相应的分页.

**Comment by mrdear** [comment]
另外还发现对于搜索出来的结果default-hover并没有生效.

主题切换过来导致很多旧文章没有配图.

**Comment by BruceYuj** [comment]
@mrdear 
1. 关于第一个bug，这两天会修复
2. 关于第二个，default-hover没有生效，你是指没有图片吗？
这是目前默认的。
![default](https://user-images.githubusercontent.com/19621739/34467867-8181f164-ef37-11e7-8d50-58e51e906281.PNG)
如果失效的话，你去dev tool看一下，是否有报错，如果有报错，可以将error贴出来

**Comment by mrdear** [comment]
搜索后src属性为 undefined,如下图
![image](https://user-images.githubusercontent.com/13889883/34467965-606d661e-ef39-11e7-9d3c-90f0cf1129b0.png)

按理来说这篇文章我没写cover应该使用默认的default-hover,但是其没有使用.

首页时正常的,目前只发现搜索页的图片src会变undefined

**Comment by BruceYuj** [comment]
@mrdear  关于archive分页我已经修复了，你可以git clone一下

**Comment by mrdear** [comment]
@BruceYuj 可真给力

**Comment by mrdear** [comment]
@BruceYuj 有点问题,点击下一页后再点击第一页,跳转的位置是首页,这里需要再修下

**Comment by BruceYuj** [comment]
@mrdear  关于你的第二个问题，经过测试没有出现你说的问题
![test](https://user-images.githubusercontent.com/19621739/34468047-fff70374-ef3a-11e7-8836-4b26bdc39ea1.PNG)

**Comment by mrdear** [comment]
看了下renderer.js的代码按理说应该是有问题的,

源代码是  `cover: post.cover || hexo.config.default_cover || hexo.theme.default_cover`

hexo.theme.default_cover这个key是错的,应该是 hexo.theme.config.default_cover

**Comment by BruceYuj** [comment]
@mrdear  这里是写错了，我没出问题是我配了根目录。 还是之前说的问题也解决了，我两个都提交了。

**Comment by mrdear** [comment]
非常感谢,已经没问题了.

我的博客也从next切过来了,哈哈,感谢提供这么优秀的主题.

贴下博客   http://mrdear.cn/

**Comment by BruceYuj** [comment]
@mrdear  以后会提供更多的配置的 <^^>
