### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by williamHappy** [Mrminfive/hexo-theme-skapp#33]
![image](https://user-images.githubusercontent.com/19304825/35023550-2021ac66-fb76-11e7-9875-5c7dd57bc169.png)
你好，可以帮忙看一下原因吗

**Comment by Mrminfive** [comment]
参照[文档](https://github.com/Mrminfive/hexo-theme-skapp/blob/master/README-cn.md#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F)

**Comment by williamHappy** [comment]
嗯   我再试试，多谢了😁😁


来自 魅族 PRO 6

-------- 原始邮件 --------
发件人：minfive <notifications@github.com>
时间：周三 1月17日 12:22
收件人：Mrminfive/hexo-theme-skapp <hexo-theme-skapp@noreply.github.com>
抄送：willHappy <ctwang1994@163.com>,Author <author@noreply.github.com>
主题：Re: [Mrminfive/hexo-theme-skapp] 安装依赖时报错 (#33)

**Comment by BruceYuj** [comment]
@williamHappy  可以参考https://github.com/Mrminfive/hexo-theme-skapp/issues/23，另外文档中也有专门针对windows的安装注意事项
