### ISSUE TITLE
Small Langauge issue

### ISSUE THREAD

**Issue by KKasbarian** [Mrminfive/hexo-theme-skapp#36]
Hi. I'm still setting and configuring this theme. There is an issue with the date that shows on small posts when I search for them.

![image](https://user-images.githubusercontent.com/20095638/35341221-963595e8-013e-11e8-99e8-9b05e235c8e5.png)
This is the home page and the month is showing in English, which is what I want. The archive page is also ok.

![image](https://user-images.githubusercontent.com/20095638/35341272-b9ff1f8a-013e-11e8-8448-168a363410f8.png)
But whenever I search for a post, the month of the resulted posts are in Chinese.

What can I do to change this language issue? I set en to the root config and it's still the same.

**Comment by BruceYuj** [comment]
@KKasbarian  Hi, I will fix it tomorrow because it's 12p.m. in China.😄

**Comment by KKasbarian** [comment]
@BruceYuj No problem! 😃

**Comment by BruceYuj** [comment]
@KKasbarian  Hi, I have fixed the bug. You can try again!

**Comment by KKasbarian** [comment]
@BruceYuj Hi, thanks. What should I do in order to get this latest version of the theme?
Also, another question, how should I contact you for more questions which are not actual issues to open here?

**Comment by BruceYuj** [comment]
![theme-pull](https://user-images.githubusercontent.com/19621739/35420649-b2ac748a-0279-11e8-8914-21cb3fb2348c.png)

@KKasbarian  
**First question**:
use your git bash.  
1. Firstly, you should change your path to your blog theme folder（like the picture）,you will find you are in the git master branch.
2. Then, use `git pull` to pull the latest code（If you change some theme files, there may be some conflict problems and you should merge firstly.）

**Second question**：
you can leave your questions at this site `https://github.com/BruceYuj/BruceYuj.github.io/issues/15`（I create this issue only for questions) or you can recommend some apps that I can use in China.

**Comment by KKasbarian** [comment]
@BruceYuj Ok, I did it and after multiple unsuccessful tries, I managed to do it (I suppose!!). But few features that I hardly changed have reverted back to original till I managed to get the latest commit from this remote. I have to do some things again! 😄

Depending on the issue or question, I'll post it on that issue or contact directly to your email. (mine is UTC +4)

Thanks for quick fixing.

**Comment by BruceYuj** [comment]
😃

**Comment by KKasbarian** [comment]
I closed the issue because this issue is fixed. 👏
