### ISSUE TITLE
站内搜索具体如何实现？

### ISSUE THREAD

**Issue by Willworkgogogo** [Mrminfive/hexo-theme-skapp#41]

**Comment by BruceYuj** [comment]
你说的是原理吗？
如果是原理你可以去研究下lunr

**Comment by Willworkgogogo** [comment]
这个站内搜索是主题自带的不需要配置对吗？我的搜索没有效果

**Comment by Mrminfive** [comment]
能准确描述下你搜索没效果是什么情况吗？

**Comment by Willworkgogogo** [comment]
blog.yalingmai.cn 右侧的搜索搜不到结果

**Comment by Mrminfive** [comment]
![image](https://user-images.githubusercontent.com/24197735/36629211-d3efbd34-198d-11e8-8250-130704526f60.png)
目测是没有生成站内词映射，正常情况下会自动在静态资源目录下生成以下词映射：
![image](https://user-images.githubusercontent.com/24197735/36629229-28e5a20e-198e-11e8-9fef-63979f559601.png)

**Comment by Willworkgogogo** [comment]
嗯，我再找找原因。感谢
