### ISSUE TITLE
link text color

### ISSUE THREAD

**Issue by upupming** [Mrminfive/hexo-theme-skapp#43]
Why is the color of the link text the same as plain text?
![image](https://user-images.githubusercontent.com/24741764/36770221-19248f9e-1c84-11e8-89b8-29ddb9ade060.png)
Where should I define the color the same as your blog?
![image](https://user-images.githubusercontent.com/24741764/36770250-420ea93a-1c84-11e8-9b9d-53e0f178701c.png)
I read the README file, shoud I configure the `_theme.scss` file in `hexo-theme-skapp/source/scss`. 
If so, how can I define it?

By the way, the README-CN.md contains some mistakes in the step of "search page".
Also some mistake in English version.
![image](https://user-images.githubusercontent.com/24741764/36770791-452b7438-1c87-11e8-9688-53507a4f3fe7.png)

**Comment by upupming** [comment]
I now add this in every md file of my post, it works:
```html
<style>
a:visited {
    color: green;
    background-color: transparent;
    text-decoration: none;
}
</style>
```
But obviously it's not wise because I have to add it to every post.

**Comment by Mrminfive** [comment]
you can change “$main-color” and “$main-color--hover” in “_theme.scss”

**Comment by upupming** [comment]
Do you means the color of link text is the same as nagivation bar?
+ $main-color: the color of the nagivation bar and link txt
+ $main-color--hover: the color of the link when we hover mouse on the link

Can I use different colors for nagivation bar and link txt?

**Comment by Mrminfive** [comment]
Yes, but you need to change the setting in "scss / base / mixins.scss" and it will change the "link" style in the article：
![2018-03-02 21_24_34-](https://user-images.githubusercontent.com/24197735/36901042-912eed1c-1e60-11e8-85ce-e55b2402fd93.png)
