### ISSUE TITLE
Error: Validation Failed.

### ISSUE THREAD

**Issue by feelscoder** [Mrminfive/hexo-theme-skapp#44]
文章底部评论部分，提示Error: Validation Failed.

**Comment by Mrminfive** [comment]
这个是因为github增加了issues标签长度的限制，等待gitalk处理

**Comment by feelscoder** [comment]
以前发的其它文章评论是没问题的，最近新发的都出现这个问题

**Comment by upupming** [comment]
gitalk已经在它的README里加了说明，我们需要自己修改一下id的配置。

https://github.com/Mrminfive/hexo-theme-skapp/pull/45
