### ISSUE TITLE
文章封面图片可以使用本地链接吗？

### ISSUE THREAD

**Issue by HPDell** [Mrminfive/hexo-theme-skapp#49]
你好：

非常喜欢你的主题。有个问题想请教一下，文章封面的链接必须挂外链吗？可不可以挂本地链接呢？

**Comment by upupming** [comment]
可以的，我的博客就是使用的本地链接，所有图片最终存放在Github上。

需要注意是应该使用绝对路径还是相对路径。

在[这里](https://upupming.site/2018/02/28/build-hexo/)“文章资源文件夹存放文章封面等图片”部分有详细说明

**Comment by HPDell** [comment]
好的~明白了。谢谢
