### ISSUE TITLE
EN Documentation

### ISSUE THREAD

**Issue by roccomuso** [Mrminfive/hexo-theme-skapp#5]
Could someone translate the documentation in english?

**Comment by BruceYuj** [comment]
After succeeding in  configuring.

**Comment by BruceYuj** [comment]
Hello, This is the [English document](https://github.com/Mrminfive/hexo-theme-skapp/blob/master/README-EN.md)

**Comment by BruceYuj** [comment]
@roccomuso

**Comment by roccomuso** [comment]
@BruceYuj thanks!
Is it worth putting it as default language?

**Comment by BruceYuj** [comment]
you mean putting the English document as the default?

**Comment by BruceYuj** [comment]
@roccomuso

**Comment by roccomuso** [comment]
@BruceYuj yep.

**Comment by BruceYuj** [comment]
@roccomuso ， That's fine. I make an issue to ask the author.

**Comment by BruceYuj** [comment]
@roccomuso,  I finish it. You can see the effect.

**Comment by roccomuso** [comment]
great!
