### ISSUE TITLE
无法安装加载lunr

### ISSUE THREAD

**Issue by Janus-Xu** [Mrminfive/hexo-theme-skapp#52]
centos7
python：2.7.14;
node:8.10.0
node-gyp:3.6.2
使用npm
![npm报错](https://user-images.githubusercontent.com/6883877/37566176-44d48ad4-2af0-11e8-9f0d-447caad03097.png)
使用cnpm

![cnpm报错](https://user-images.githubusercontent.com/6883877/37566181-6b39b6d6-2af0-11e8-8370-912d02c09987.jpg)
虽然node_modules找到了_lunr@0.7.1@lunr和_nodejieba@2.2.5@nodejieba
试了下果然还是无法启动
![tim 20180318210903](https://user-images.githubusercontent.com/6883877/37566188-a2234112-2af0-11e8-951a-87a477f6c9c7.jpg)

**Comment by upupming** [comment]
图一没有权限，加上sudo

图二没安装g++，make中断
