### ISSUE TITLE
_config.yml配置

### ISSUE THREAD

**Issue by williamHappy** [Mrminfive/hexo-theme-skapp#55]
![image](https://user-images.githubusercontent.com/19304825/39281680-7a229a80-4938-11e8-992a-1389a89aa630.png)
这些配置是写到blog目录下的_config.yml还是主题文件下的_config.yml

**Comment by BruceYuj** [comment]
blog目录下的

**Comment by williamHappy** [comment]
我依赖都安装了，但是hexo s还是跑不起来
![image](https://user-images.githubusercontent.com/19304825/39283804-a3cfc164-4942-11e8-8363-70c73d9e1308.png)
麻烦你帮看下，谢谢

**Comment by BruceYuj** [comment]
nodejieba报错，具体导致原因不知，你可以先试下去掉路径的中文符号

**Comment by williamHappy** [comment]
嗯嗯 刚刚也感觉是这个问题，我来试试，^-^

**Comment by williamHappy** [comment]
@BruceYuj  哈哈  我想起来了  我加过你微信哈哈 看到你blog，突然想起来了

**Comment by williamHappy** [comment]
当时也遇到过404的问题 ，忘记怎么搞的了

**Comment by BruceYuj** [comment]
好像github评论出bug了，手机端收到你的评论邮件，PC端看不到内容

**Comment by williamHappy** [comment]
哈哈  没有  我删除了，知道为啥了，就删了
