### ISSUE TITLE
执行hexo g的一个报错

### ISSUE THREAD

**Issue by Demonsq** [Mrminfive/hexo-theme-skapp#56]
issues里好像没看到有人出现这种问题，
![image](https://user-images.githubusercontent.com/19154386/39583852-9debe584-4f23-11e8-820c-216fe6b7149d.png)

**Comment by BruceYuj** [comment]
searchIdx 是lunr返回的一个对象，是不是你的lunr安装有问题

**Comment by Demonsq** [comment]
我重装了一下lunr还是这样，，，lunr版本是2.2.0

**Comment by BruceYuj** [comment]
你去renderer.js文件打印下searchIdx对象，看看是个什么结果。

**Comment by Demonsq** [comment]
是这样输出吗，，没用过nodejs![image](https://user-images.githubusercontent.com/19154386/39584987-4b54932c-4f26-11e8-9b86-3ff206f8c595.png)

**Comment by BruceYuj** [comment]
明天帮你看一看

**Comment by Demonsq** [comment]
好的，谢谢了

**Comment by Demonsq** [comment]
看来还是因为版本的原因。。
![image](https://user-images.githubusercontent.com/19154386/39586859-bb66f1b0-4f2a-11e8-9c8a-45de3810fc6d.png)
我把searchIdx赋值的语句放到了原来的searchIdx.add那，然后出来了下面这两个错误
![image](https://user-images.githubusercontent.com/19154386/39587517-4d7febb4-4f2c-11e8-84b0-06532fe0cf18.png)
![image](https://user-images.githubusercontent.com/19154386/39587574-69494ca0-4f2c-11e8-8224-d9ea7c042e8b.png)

**Comment by BruceYuj** [comment]
问一下，你的lunr是 mamboer/lunr.js吗？

**Comment by Demonsq** [comment]
好像是这个https://github.com/olivernn/lunr.js
我直接npm install 安装的

**Comment by BruceYuj** [comment]
readme当中应该是 mamboer/lunr.js. 你先卸载之前的，重新安装mamboer的。这个支持中文

**Comment by Demonsq** [comment]
好的，谢谢
