### ISSUE TITLE
样式问题（SCSS无法自动转换成CSS）

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#6]
SCSS需要自己手动来编译。

**Comment by Mrminfive** [comment]
不好意思，之前文档根_config.yml中漏了sass及autoprefixer配置，所以无法自动编译sass，请见谅。

**Comment by BruceYuj** [comment]
page/search.scss中的：
```
    @keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) },
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }
```
按照CSS3中的写法，不是应该没有逗号的吗？
```
    @keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) }
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }
```

**Comment by BruceYuj** [comment]
http://www.w3school.com.cn/cssref/pr_keyframes.asp

**Comment by Mrminfive** [comment]
好的

发自我的 iPhone

在 2017年10月12日，01:17，JunYu <notifications@github.com<mailto:notifications@github.com>> 写道：


http://www.w3school.com.cn/cssref/pr_keyframes.asp
