### ISSUE TITLE
急~使用gitalk无法评论

### ISSUE THREAD

**Issue by feelscoder** [Mrminfive/hexo-theme-skapp#63]
评论文章使用github登录时总是跳转到首页，然后再点金进入文章详情，显示还是未登录状态

**Comment by BruceYuj** [comment]
你有更新过skapp吗？因为之前github对于issue长度做过限制，导致gitalk失败。
我这边测试是没有问题的

**Comment by feelscoder** [comment]
之前好像更新了，gitalk目前配置是这样的：
var gitalk = new Gitalk({
            clientID: '{{ config.gitTalk.clientId }}',
            clientSecret: '{{ config.gitTalk.clientSecret }}',
            repo: '{{ config.gitTalk.repo }}',
            owner: '{{ config.gitTalk.owner }}',
            admin: [{% for item in config.gitTalk.admin %}'{{ item }}', {% endfor %}],
            labels: tags,
            id: (new Date({{ page.date }})).getTime() > (new Date('2018-02-15')).getTime() ? md5(location.href) : location.href
        });

        gitalk.render('gitalk-container');

关键是有的人可以评论成功，有的就是出现我刚说的那种情况

**Comment by feelscoder** [comment]
http://maliquankai.com/2018/05/24/MiniHour%20—%20时刻关注你的目标时间/，这个是访问地址，大佬可以试试，经常出现这个问题

**Comment by BruceYuj** [comment]
我看只有这个URL会出现这个问题，但是你其他文章并不会出现该问题是吧

**Comment by feelscoder** [comment]
其它文章，点击GitHub登录跳转到404页面了

**Comment by feelscoder** [comment]
有些会，有些又不会，比如这个
http://maliquankai.com/2018/04/05/许久不见，甚是想念，送福利了！/

**Comment by feelscoder** [comment]
是不是标题不能出现标点符号之类的，这个怎么规避呢？

**Comment by BruceYuj** [comment]
报的是redirect_uri_mistach，就是注册的url和redirect url不同。有可能是中文或中文符号的问题。

**Comment by feelscoder** [comment]
对，应该是中午符号的问题

**Comment by BruceYuj** [comment]
正常推荐的是在写md文件命名的时用全英文的方式，然后具体题目名写在markdown文件title里面。
`2018-5-23-pseudo-classes-and-pseudo-elements.md`
`title: 中文题目`

**Comment by BruceYuj** [comment]
我看了你的blog，设计的非常好看。

**Comment by feelscoder** [comment]
哈哈，谢谢，我正在改md文件命名，也谢谢你这么及时的帮我解决问题

**Comment by BruceYuj** [comment]
你先改一个测试看看是否是中文导致的问题。

**Comment by feelscoder** [comment]
改一个测试了，是中文字符导致的

**Comment by feelscoder** [comment]
我发现配置那里下面这句admin: [{% for item in config.gitTalk.admin %}'{{ item }}', {% endfor %}],
我改成这个了admin: ['{{ config.gitTalk.admin }}'],不然就会出现登录成功就出现这样的报错信息：


未找到相关的 Issues 进行评论
请联系 @f @e @e @l @s @c @o @d @e @r 初始化创建

**Comment by feelscoder** [comment]
改了md文件命名，以前的评论都见了😢

**Comment by BruceYuj** [comment]
应该是有办法移植的，因为所有的评论都在你的blog issue里面。

**Comment by feelscoder** [comment]
@BruceYuj 大佬能支个招迁移一下吗？

**Comment by BruceYuj** [comment]
今天没啥时间，等周末放假的。

**Comment by feelscoder** [comment]
好的，我先自己尝试下

**Comment by feelscoder** [comment]
好，我以为改一下issue哪里的链接应该可以关联过去，结果不起作用，最新发的文章下周一抽奖😢，有没有可以临时关联过去的办法

**Comment by BruceYuj** [comment]
gitalk应该是通过label来区分issue的，你可以从这方面解决

**Comment by feelscoder** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/10194861/40471460-54c7d344-5f69-11e8-9afc-5ce9ef6c40a8.png">
能看到图吗？创建了这么多个issue

**Comment by BruceYuj** [comment]
我刚刚注意到这个问题了，应该是gitalk本身的问题。gitalk的issue里面有同样的问题。准备有空研究下。

**Comment by feelscoder** [comment]
忧伤，我也看一下怎么关联以前的评论

**Comment by feelscoder** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/10194861/40474257-1e66a192-5f71-11e8-8774-28528d023cf5.png">
有些文章详情，登陆之后又出现这个

**Comment by Mrminfive** [comment]
因为无法确定 github 该策略的具体时间，只能够大致估算一个时间为界限进行适配，这中间可能会有一些文章丢失的
