### ISSUE TITLE
版本切换为8.9.3仍然在lunr.js安装失败

### ISSUE THREAD

**Issue by kiros666** [Mrminfive/hexo-theme-skapp#64]
[@mamboer/lunr.js] install  from git github:mamboer/lunr.js, may be very slow, please keep patience
\ [0/1] Installing nan@~2.10.0
C:\Users\Administrator\Desktop\blog\blog\node_modules\_nodejieba@2.2.6@nodejieba>node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
- [0/1] Installing nan@~2.10.0在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
\ [0/1] Installing nan@~2.10.0MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft
 Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\Users\Administrator\Desktop\blog\blo
g\node_modules\_nodejieba@2.2.6@nodejieba\build\binding.sln]
| [0/1] Installing nan@~2.10.0gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\nodejs\\8.9.3\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Desktop\blog\blog\node_modules\_nodejieba@2.2.6@nodejieba
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
× Install fail! Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npminstall version: 3.6.2
npminstall args: D:\nodejs\8.9.3\node.exe C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\Administrator\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org --save mamboer/lunr.js

**Comment by zhililab** [comment]
@kiros666 我也是同样的问题 T_T

**Comment by BruceYuj** [comment]
mac 还是 windows

**Comment by kiros666** [comment]
@BruceYuj windows

**Comment by Mrminfive** [comment]
主要还是 nodejieba 的问题，参见文档
