### ISSUE TITLE
请问markdown语法如何高亮

### ISSUE THREAD

**Issue by lyubingo** [Mrminfive/hexo-theme-skapp#66]
我用的markdown，但是有些不兼容，

比如编辑器缩进表示一段，编译器需要三个反引号```

比如 ## 后面要接空格，

这些都是小事，今天我发现，同样的模板，怎么你们有语法高亮！，

我的都是全黑色的。。。哪个好心的可以告诉我怎么使用高亮吗？

https://lyubingo.github.io 我的没有高亮
http://blog.minfive.com/  demo是有的
https://mrdear.cn/  这位大神的也有，而且很漂亮（我其实是参照他做的啦）

谢谢：）

**Comment by BruceYuj** [comment]
@lyubingo  你说的是代码高亮吗？
如果是代码的话
你使用```后面需要加具体的语言比如`css`
