### ISSUE TITLE
theme问题：自动生成的html文件引入的js路径有问题

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#7]
localhost/:170 GET http://localhost:4000/about/js/common/utils.js 
localhost/:171 GET http://localhost:4000/about/js/common/pack.js 
localhost/:172 GET http://localhost:4000/about/js/common/animation.js 
localhost/:173 GET http://localhost:4000/about/js/layout/loading.js 
localhost/:174 GET http://localhost:4000/about/js/layout/header.js 
localhost/:175 GET http://localhost:4000/about/js/layout/back-top.js 
localhost/:176 GET http://localhost:4000/about/js/layout/post.js 
localhost/:171 GET http://localhost:4000/about/js/common/pack.js 
localhost/:172 GET http://localhost:4000/about/js/common/animation.js 
localhost/:173 GET http://localhost:4000/about/js/layout/loading.js 
localhost/:174 GET http://localhost:4000/about/js/layout/header.js 
localhost/:175 GET http://localhost:4000/about/js/layout/back-top.js 
localhost/:176 GET http://localhost:4000/about/js/layout/post.js

**Comment by BruceYuj** [comment]
是不是build common.js出错

**Comment by BruceYuj** [comment]
今天正好有空修改相关的swig文件。
所有js模板引入的路径都添加了 / ，错误修正了。可能是不是系统兼容性的问题。

**Comment by Mrminfive** [comment]
主题使用filter_cleanup插件处理css、js、图片以及其它静态资源，插件使用了html-minifier库，用于合并js文件，所以原先写法是正确的，有问题的话请检查根_config.yml中的配置是否于README中的基本配置相同。

**Comment by BruceYuj** [comment]
配置是按照README.md的配置的，首页不会出现问题。跳转到其他页面的时候，外部js的地址会出错（这些js文件，我看你的网站代码应该是在根目录下的）

**Comment by BruceYuj** [comment]
![blog-layout](https://user-images.githubusercontent.com/19621739/31445891-b85d0b0c-aed1-11e7-9030-7395ff140f34.PNG)

**Comment by BruceYuj** [comment]
这是修改后的

**Comment by Mrminfive** [comment]
你可以检查下出错页面的js是否合并为common，如果分散为多个js那么就是插件没有执行到

**Comment by BruceYuj** [comment]
没有合并为common

**Comment by BruceYuj** [comment]
是不是也需要在_config.yml中配置hexo-filter-cleanup

**Comment by Mrminfive** [comment]
确认过根_config.yml配置正确的化，可以检查下node依赖是否安装正确，建议删除 node_modules 后重新安装依赖。

**Comment by BruceYuj** [comment]
我重新新建了一个新的blog目录，然后按照README重头开始配置，发现hexo-filter-cleanup和node-sass两个插件都没有起作用

**Comment by BruceYuj** [comment]
node_modules也查看过了，几个插件都有安装。

**Comment by BruceYuj** [comment]
插件都是安装在根目录下面的node_modules吧？

**Comment by Mrminfive** [comment]
对的

发自我的 iPhone

在 2017年10月11日，23:05，JunYu <notifications@github.com<mailto:notifications@github.com>> 写道：


插件都是安装在根目录下面的node_modules吧？

**Comment by Mrminfive** [comment]
使用根_config.yml中的配置进行调用

发自我的 iPhone

在 2017年10月11日，23:09，JunYu <notifications@github.com<mailto:notifications@github.com>> 写道：


hexo-filter-cleanup和node-sass这两个插件的具体代码是在哪里呢？我在renderer.js和helper.js里面都没有看到具体的使用代码

**Comment by BruceYuj** [comment]
>I completely re-wrote this hexo filter plugin because hexo-all-minifier has certain issues as below which sucks my hexo project on mac osx platform. Besides that i have added some other cool features like useref and performance improvements.

我看了下hexo-filter-cleanup，作者在写这个插件的时候，是为了macos来写的，会不会是由于系统不同的原因呢？
我准备用hexo-all-minifier来试一下

**Comment by BruceYuj** [comment]
经过重新安装验证，发现是
search.swig中的：
```  
<!-- build:js /js/search.js -->
        <script type="text/javascript" src="js/libs/axios.min.js"></script>
        <script type="text/javascript" src="js/libs/lunr.min.js"></script>
        <script type="text/javascript" src="js/page/search.js"></script>
    <!-- endbuild -->
```
_layout.swig中的：
```
    <!-- build:js /js/common.js -->
        <script type="text/javascript" src="js/common/utils.js"></script>
        <script type="text/javascript" src="js/common/pack.js"></script>
        <script type="text/javascript" src="js/common/animation.js"></script>
        <script type="text/javascript" src="js/layout/loading.js"></script>
        <script type="text/javascript" src="js/layout/header.js"></script>
        <script type="text/javascript" src="js/layout/back-top.js"></script>
        <script type="text/javascript" src="js/layout/post.js"></script>
    <!-- endbuild -->
```
这两段代码，build并没有进行，根据hexo-filter-cleanup插件的README来看，这是为了macosx来写的插件，可能并不适用于Windows系统，因此在win下，需要写完整的路径.类似下面的代码
```
        <script type="text/javascript" src="/js/layout/post.js"></script>
```
或者直接手动合并压缩js代码也可。

**Comment by BruceYuj** [comment]
作者你可以在README.me备注一下win下安装可能会出现的问题

**Comment by Mrminfive** [comment]
不太可能是因为系统原因，编译的时候时候是否有错误提示？

**Comment by BruceYuj** [comment]
hexo s开启本地服务器（已hexo clean过），编译不会报错。然后开始请求根目录下具体的子目录（比如具体的post文章页面），会404（也就是最开始的url拼接错误）。

然后，使用hexo g，common目录下的js也没有合并。

**Comment by BruceYuj** [comment]
实际上应该有的效果应该这些js会concat（也是hexo-filter-cleanup比hexo-all-minifier多的功能）成一个js。

但是在win10下面这些js并没有合并。

**Comment by Mrminfive** [comment]
刚翻了一下源码，可能是因为系统环境路径分割符的影响，我找个时间解决一下

**Comment by BruceYuj** [comment]
我看了hexo-filter-cleanup的源码，concat功能使用的useref模块，useref模块在解析生成的html文档的时候，并没有将script和css模块分解出来。
我打印这一块内容时，为空数组。
（具体文件位置：useref.js的82行`let result = useref(str)`）

**Comment by BruceYuj** [comment]
我仔细的看了下useref的源码，然后发现在concat代码中，解析html文件时，发现被解析的html文件已经被压缩过了（具体就是去掉了所有的注释和换行符，而useref就是通过注释和换行符来解析合并外部js代码的），也就是说，不是系统环境路径分隔符的影响。

然后我仔细想了想，原因是我之前尝试使用了hexo-all-minifier --save(将该插件配置到了package.json当中)，而minifier和cleanup的配置信息是有重复的，也就会先压缩原有的html文件。

而最开始不能成功的原因，没有发现（可能还是和配置有关）。

##总结
该问题，可以直接通过目前的README.md来正常安装（不用区分win和macos）
