### ISSUE TITLE
部署上去 ，没有显示图标

### ISSUE THREAD

**Issue by jerryc127** [Mrminfive/hexo-theme-skapp#70]
照着README 
该安装的都安装了
但是部署上去 没有了图标
hexo clean hexo g hexo d 都没有报错
![image](https://user-images.githubusercontent.com/16351105/42419191-6ac8d656-82e2-11e8-89ee-a9ca98ef296a.png)
![image](https://user-images.githubusercontent.com/16351105/42419194-713b38f8-82e2-11e8-9fb5-d5a570687d83.png)
![image](https://user-images.githubusercontent.com/16351105/42419195-7ecdf9e2-82e2-11e8-8d88-7d34edcd42d6.png)

blog: jerryc.me

**Comment by Mrminfive** [comment]
资源引用路径出错了

**Comment by jerryc127** [comment]
具体在哪修改，我没动过这些资源路径啊

**Comment by WeiXiang666** [comment]
同样的问题，我执行下面命令莫名就好了
$ hexo clean
$ hexo generate --deploy

**Comment by Mrminfive** [comment]
清除缓存，楼上的方法是对的
