### ISSUE TITLE
page/search.scss 编译报错

### ISSUE THREAD

**Issue by BruceYuj** [Mrminfive/hexo-theme-skapp#8]
@keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) },
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }
改为
    @keyframes loader {
        from { transform: translate(-50%, -50%) rotate(0) }；
        to { transform: translate(-50%, -50%) rotate(360deg) }
    }

**Comment by Mrminfive** [comment]
Duplicate of #6
