### ISSUE TITLE
文章的分类要怎么设置？

### ISSUE THREAD

**Issue by lingchuanzhou** [Mrminfive/hexo-theme-skapp#83]
文章的分类要怎么设置？就是侧边栏的这个：

“文章分类
读书笔记1
经验总结4
日常学习9
文章转发1”

**Comment by Mrminfive** [comment]
参见 [hexo 文档](https://hexo.io/zh-cn/docs/front-matter#%E5%88%86%E7%B1%BB%E5%92%8C%E6%A0%87%E7%AD%BE)
